In [1]:
import pandas as pd
from sklearn import metrics

In [2]:
import numpy as np

In [3]:
df=pd.read_csv("D:\Datasets\Luminar\drug200.csv")


In [4]:
df


Age Sex      BP Cholesterol  Na_to_K   Drug
0     23   F    HIGH        HIGH   25.355  DrugY
1     47   M     LOW        HIGH   13.093  drugC
2     47   M     LOW        HIGH   10.114  drugC
3     28   F  NORMAL        HIGH    7.798  drugX
4     61   F     LOW        HIGH   18.043  DrugY
..   ...  ..     ...         ...      ...    ...
195   56   F     LOW        HIGH   11.567  drugC
196   16   M     LOW        HIGH   12.006  drugC
197   52   M  NORMAL        HIGH    9.894  drugX
198   23   M  NORMAL      NORMAL   14.020  drugX
199   40   F     LOW      NORMAL   11.349  drugX

[200 rows x 6 columns]

In [5]:
df['Sex'].unique()
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()
df['Sex']=label_encoder.fit_transform(df['Sex'])
df['Sex'].unique()

array([0, 1])

In [6]:
df['BP'].unique()
df['BP']=label_encoder.fit_transform(df['BP'])
df['BP'].unique()

array([0, 1, 2])

In [7]:
df['Cholesterol'].unique()
df['Cholesterol']=label_encoder.fit_transform(df['Cholesterol'])
df['Cholesterol'].unique()

array([0, 1])

In [8]:
df


Age  Sex  BP  Cholesterol  Na_to_K   Drug
0     23    0   0            0   25.355  DrugY
1     47    1   1            0   13.093  drugC
2     47    1   1            0   10.114  drugC
3     28    0   2            0    7.798  drugX
4     61    0   1            0   18.043  DrugY
..   ...  ...  ..          ...      ...    ...
195   56    0   1            0   11.567  drugC
196   16    1   1            0   12.006  drugC
197   52    1   2            0    9.894  drugX
198   23    1   2            1   14.020  drugX
199   40    0   1            1   11.349  drugX

[200 rows x 6 columns]

In [9]:
X=df.iloc[:,:-1].values
y=df.iloc[:,-1].values


In [10]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.30)


In [12]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(X_train)
X_train=scaler.transform(X_train)
X_test=scaler.transform(X_test)

In [13]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(X_train,y_train)

GaussianNB()

In [14]:
y_pred=model.predict([[18,1,1,0,20]])

In [15]:
print(y_pred)

['DrugY']


In [19]:
from sklearn.metrics import confusion_matrix,accuracy_score
y_pred = model.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
ac = accuracy_score(y_test, y_pred)
print(cm)
print(ac)

[[20  6  1  4  1]
 [ 0  7  0  0  0]
 [ 0  0  2  0  0]
 [ 0  0  0  4  0]
 [ 0  0  0  0 15]]
0.8
